import { describe, expect, it } from 'vitest';
import { initialDemoState } from '@/lib/demo-data';
import { draftPacket } from '@/lib/drafting';
import { selectApplication, setPacket, approveFill, hasFillApproval } from '@/lib/workflow';
import { canReopenManualAttempt, formFieldValue } from '@/lib/form-review';
import { reopenManualAttempt } from '@/lib/submission-recovery';
async function fixture(){const state=initialDemoState();const app=selectApplication(state,state.jobs[0].id,state.profile.id);const packet=await draftPacket(state.profile,state.jobs[0]);packet.answers=[];setPacket(state,app,packet);approveFill(app,state.profile.id,app.packetHash!,state.jobs[0].applyUrl);app.status='uncertain';app.manualSubmissionReport={source:'owner',outcome:'unconfirmed',reportedAt:new Date().toISOString(),siteMessage:'Spam block'};app.browserSessionId='expired';app.form={version:1,url:state.jobs[0].applyUrl,hash:'old',capturedAt:'2026-09-30T20:27:00Z',fields:[{label:'First name',kind:'text',value:''}],attachments:[],readyToSubmit:false};return {state,app};}
describe('manual failure review',()=>{
 it('archives the old snapshot and approval, preserves the packet, and requires fresh fill approval',async()=>{const {state,app}=await fixture();const packet=structuredClone(app.packet);const previousForm=structuredClone(app.form);const previousApprovals=structuredClone(app.approvals);reopenManualAttempt(app,state.profile.id,true);expect(app.status).toBe('draft_review');expect(app.packet).toEqual(packet);expect(app.form).toBeUndefined();expect(app.browserSessionId).toBeUndefined();expect(app.queuedRun).toBeUndefined();expect(app.approvals).toEqual([]);expect(app.manualSubmissionReport?.resolution?.previousForm).toEqual(previousForm);expect(app.manualSubmissionReport?.resolution?.previousApprovals).toEqual(previousApprovals);expect(hasFillApproval(app,state.profile.id,state.jobs[0].applyUrl)).toBe(false);expect(app.transitionHistory?.at(-1)).toMatchObject({from:'uncertain',to:'draft_review'});});
 it('rejects missing confirmation and another owner without changing any state',async()=>{for(const [owner,confirmed] of [['other-user',true],['demo-user',false]] as const){const {app}=await fixture();const before=structuredClone(app);expect(()=>reopenManualAttempt(app,owner,confirmed)).toThrow();expect(app).toEqual(before);}});
 it.each(['agent-started','agent-clicked','agent-worker','receipt','submitted','submit-approval','queued','no-report','already-reviewed'])('does not reopen %s as a manual-only failure',async(mode)=>{const {app,state}=await fixture();if(mode==='agent-started')app.submissionStartedAt=app.updatedAt;if(mode==='agent-clicked')app.submissionAttemptedAt=app.updatedAt;if(mode==='agent-worker')app.submissionWorkerClaimedAt=app.updatedAt;if(mode==='receipt')app.submissionReceipt={version:1,url:app.form!.url,text:'Ambiguous',capturedAt:app.updatedAt};if(mode==='submitted')app.submittedAt=app.updatedAt;if(mode==='submit-approval')app.approvals.push({...app.approvals[0],kind:'submit'});if(mode==='queued')app.queuedRun={id:'queued',kind:'fill',requestedAt:app.updatedAt,reason:'waiting'};if(mode==='no-report')app.manualSubmissionReport=undefined;if(mode==='already-reviewed')app.manualSubmissionReport!.resolution={outcome:'not_accepted',reviewedAt:app.updatedAt,previousApprovals:[]};expect(canReopenManualAttempt(app)).toBe(false);const before=structuredClone(app);expect(()=>reopenManualAttempt(app,state.profile.id,true)).toThrow();expect(app).toEqual(before);});
});
describe('reviewed control values',()=>{
 it('never presents native radio on values as filled or selected',()=>{expect(formFieldValue({label:'Yes',value:'on',kind:'radio',checked:false})).toBe('Not selected');expect(formFieldValue({label:'No',value:'on',kind:'radio',checked:true})).toBe('Selected');expect(formFieldValue({label:'Authorization',value:'Yes',kind:'radio',checked:true})).toBe('Yes · Selected');});
});
