import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { chromium } from "playwright-core";
import { initialDemoState } from "../src/lib/demo-data";
import { publicState } from "../src/lib/public-state";
import { updateJobFeedback } from "../src/lib/job-feedback";
import { matchKey } from "../src/lib/match-cache";
import { assessMatchLocally } from "../src/lib/matching";

async function main() {
  const origin = process.env.TEST_MATCHES_URL || "http://localhost:3008";
  const demoState = initialDemoState();
  demoState.jobs.forEach((job, index) => { job.postedAt = new Date(Date.now() - index * 86400000).toISOString(); });
  const intern = demoState.jobs.find(job => job.id === "demo-engineering-intern")!;
  // Deliberately exercise a high-fit assessment with unresolved eligibility;
  // ranking policy changes must not remove this presentation regression case.
  demoState.matchCache = { [matchKey(demoState.profile, intern)]: { ...assessMatchLocally(demoState.profile, intern), category: "strong" } };
  let fixture = publicState(demoState);
  let failFeedback = false;
  let malformedFeedback = false;
  let slowFeedback = false;
  let failRefresh = false;
  let failImport = false;
  let malformedImport = false;
  let authImport = false;
  let authFeedback = false;
  let feedbackRequests = 0;
  const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_EXECUTABLE_PATH || undefined });
  try {
    const page = await browser.newPage();
    // Drive the shipped component with invented applicant/jobs. No account,
    // provider calls, application approvals or submissions are involved.
    await page.route("**/api/state", route => { if (failRefresh) { failRefresh = false; return route.fulfill({ status: 503, json: { error: "Invented refresh failure" } }); } return route.fulfill({ json: fixture }); });
    await page.route("**/api/status", route => route.fulfill({ contentType: "text/event-stream", body: `event: state\ndata: ${JSON.stringify(fixture)}\n\n` }));
    await page.route("**/api/actions", async route => {
      const body = route.request().postDataJSON();
      if (body.action === "import") {
        if (authImport) { authImport = false; return route.fulfill({ status: 401, json: { error: "AUTH_REQUIRED" } }); }
        if (fixture.jobs.some(job => job.url === body.payload.url)) return route.fulfill({ status: 409, json: { error: "This link is already in your catalog." } });
        if (malformedImport) { malformedImport = false; return route.fulfill({ status: 502, contentType: "text/html", body: "<html>Invented gateway failure</html>" }); }
        if (failImport) { failImport = false; return route.fulfill({ status: 503, json: { error: "Posting unavailable. Check the link or try later." } }); }
        await new Promise(resolve => setTimeout(resolve, 750));
        const job = { ...intern, id: "synthetic-import", company: body.payload.company, title: body.payload.title, url: body.payload.url, importUrl: body.payload.url, requirements: [], source: "imported" as const, sourceLabel: "Imported link", importCheck: { status: "manual" as const, checkedAt: new Date().toISOString() } };
        fixture.jobs.push(job);
        fixture.matches.push({ jobId: job.id, assessment: assessMatchLocally(fixture.profile, job) });
        return route.fulfill({ json: { ok: true } });
      }
      feedbackRequests++;
      assert.equal(body.action, "feedback", "Only synthetic feedback/import actions are allowed in this test");
      assert.ok(["saved", "dismissed", "clear"].includes(body.payload.kind));
      if (malformedFeedback) { malformedFeedback = false; return route.fulfill({ status: 502, contentType: "text/html", body: "<html>Invented gateway failure</html>" }); }
      if (authFeedback) { authFeedback = false; return route.fulfill({ status: 401, json: { error: "AUTH_REQUIRED" } }); }
      if (failFeedback) { failFeedback = false; return route.fulfill({ status: 503, json: { error: "Feedback could not be saved. Try again." } }); }
      if (slowFeedback) { slowFeedback = false; await new Promise(resolve => setTimeout(resolve, 750)); }
      updateJobFeedback(fixture, body.payload);
      return route.fulfill({ json: { ok: true } });
    });
    await mkdir(".data", { recursive: true });
    for (const [label, width, height] of [["desktop", 1440, 1000], ["mobile", 390, 844]] as const) {
      await page.setViewportSize({ width, height });
      fixture = publicState(structuredClone(demoState));
      await page.goto(origin);
      const strongRole = page.getByRole("article", { name: "Software Engineering Intern Cedar Systems", exact: true });
      await strongRole.waitFor();
      if (label === "desktop") {
        const activity = page.locator("#matches-activity");
        const activityLauncher = page.getByRole("button", { name: "Activity", exact: true });
        assert.equal(await activity.isVisible(), false, "Quiet activity should leave room for role review");
        await activityLauncher.click();
        await activity.getByRole("heading", { name: "Agent activity", exact: true }).waitFor();
        assert.equal(await activity.getByText("Demo listings do not run live source checks.", { exact: true }).isVisible(), true);
        assert.equal(await activity.getByText("About every 4 hours", { exact: true }).count(), 0);
        await page.keyboard.press("Escape");
        assert.equal(await activity.isVisible(), false);
        assert.equal(await activityLauncher.evaluate(element => element === document.activeElement), true);
      }
      assert.equal(await strongRole.getByText("Strong fit", { exact: true }).isVisible(), true);
      const context = "Software Engineering Intern at Cedar Systems";
      const jobButton = (name: string) => strongRole.getByRole("button", { name: `${name} ${context}`, exact: true });
      assert.equal(await page.locator(".profile-context").getByText("Work authorization needs confirmation.", { exact: true }).isVisible(), true, "Strong fit must not conceal unresolved eligibility information");
      const setup = page.locator(".setup-context");
      assert.equal(await setup.isVisible(), true, "Incomplete setup must be discoverable before the role list");
      await setup.locator("summary").click();
      assert.equal(await setup.getByRole("list").getByText("sponsorship answer", { exact: true }).isVisible(), true);
      await setup.getByRole("button", { name: "Review profile", exact: false }).click();
      await page.getByRole("heading", { name: "Your profile", exact: true }).waitFor();
      assert.equal(await page.locator("#setup-workAuthorization").evaluate(element => element === document.activeElement), true, "Setup action focuses the next missing answer");
      await page.getByRole("button", { name: "Matches", exact: true }).click();
      assert.equal(await setup.getAttribute("open"), null);
      assert.equal(await strongRole.locator(".fit-highlight").isVisible(), true, "Show positive evidence without opening details");
      assert.equal(await strongRole.locator(".preparation-note").count(), 0, "Shared preparation guidance must not repeat in every role");
      await page.evaluate(() => window.scrollTo(0, 0));
      const firstRoleBox = await page.getByRole("article").first().boundingBox();
      assert.ok(firstRoleBox && firstRoleBox.y < height, "The first role must begin in the initial viewport");
      assert.equal(await strongRole.locator(".fit-highlight").innerText(), "Posting: React · Your confirmed experience: Built a React portfolio project");
      if (label === "mobile") {
        const prepareBox = await jobButton("Prepare application for").boundingBox();
        assert.ok(prepareBox && prepareBox.y + prepareBox.height <= height, "One complete opportunity and its preparation action should fit in the opening phone viewport");
      }
      if (label === "mobile") {
        const morePages = page.getByRole("button", { name: "More pages", exact: true });
        await morePages.click();
        await page.getByRole("link", { name: "AI usage", exact: true }).waitFor();
        await page.locator("#more-pages").getByRole("button", { name: "Agent activity", exact: true }).click();
        await page.locator("#matches-activity").getByRole("heading", { name: "Agent activity", exact: true }).waitFor();
        await page.keyboard.press("Escape");
        assert.equal(await page.locator("#matches-activity").isVisible(), false);
        assert.equal(await page.locator("#more-pages").getByRole("button", { name: "Agent activity", exact: true }).evaluate(element => element === document.activeElement), true, "Closing nested activity returns focus to its More entry");
        await page.keyboard.press("Escape");
        await page.waitForFunction(() => document.activeElement?.getAttribute("aria-label") === "More pages");
        assert.equal(await morePages.evaluate(element => element === document.activeElement), true, "Closing auxiliary navigation restores focus");
        await page.getByRole("button", { name: /^Filter and sort/ }).click();
      }
      assert.equal(await page.getByRole("combobox", { name: "Sort roles" }).getAttribute("aria-describedby"), "sort-help");
      assert.equal(await page.getByText("Relevance considers fit and your feedback.", { exact: true }).isVisible(), true);
      await page.locator(".fit-guide summary").click();
      assert.equal(await page.getByText("Fit compares the posting with your confirmed profile and search preferences. It does not confirm eligibility or guarantee an offer.", { exact: true }).isVisible(), true);
      await page.locator(".fit-guide summary").click();
      assert.equal(await strongRole.locator(".match-reasons").isVisible(), false, "Full reasoning is disclosed on request");
      await strongRole.locator(".fit-evidence summary").click();
      assert.equal(await strongRole.locator(".evidence-comparison").getByText("Built a React portfolio project", { exact: true }).isVisible(), true);
      assert.equal(await strongRole.locator(".match-reasons").getByText("No confirmed evidence yet for TypeScript.", { exact: true }).isVisible(), true, "Disclosure must preserve every missing requirement");
      await strongRole.locator(".fit-evidence summary").click();
      const query = page.getByRole("searchbox", { name: "Search roles or companies" });
      await query.fill("cedar engineering");
      assert.equal(await page.getByRole("article").count(), 1, "Search matches company and title case-insensitively");
      assert.equal(await page.getByRole("button", { name: "Any fit 1", exact: true }).isVisible(), true);
      assert.equal(await page.getByRole("button", { name: "Strong 1", exact: true }).isVisible(), true);
      assert.equal(await page.getByRole("button", { name: "Possible 0", exact: true }).isVisible(), true);
      assert.equal(await page.locator(".result-summary").innerText(), '1 role in all roles for “cedar engineering”');
      await query.fill("no-company-has-this-name");
      await page.getByRole("heading", { name: "No roles match your search", exact: true }).waitFor();
      await page.getByRole("button", { name: "Clear search", exact: true }).last().click();
      assert.equal(await page.getByRole("article").count(), 3);
      await page.getByRole("combobox", { name: "Sort roles" }).selectOption("newest");
      assert.equal(await page.getByRole("article").first().getByRole("heading").innerText(), "Junior Product Analyst");
      await page.getByRole("combobox", { name: "Sort roles" }).selectOption("relevant");
      const savedBox = await page.getByRole("button", { name: "Saved 0", exact: true }).boundingBox();
      assert.ok(savedBox && savedBox.x >= 0 && savedBox.x + savedBox.width <= width, "Saved must be visible without horizontal filter scrolling");
      const launcher = page.getByRole("button", { name: "+ Import a job link", exact: true });
      await launcher.click();
      const dialog = page.getByRole("dialog", { name: "Import a job link" });
      await dialog.waitFor();
      assert.equal(await page.getByRole("textbox", { name: "Job URL (required)", exact: true }).evaluate(element => element === document.activeElement), true, "Opening import moves focus into its input");
      for (let step = 0; step < 9; step++) {
        await page.keyboard.press("Tab");
        assert.equal(await dialog.evaluate(element => element.contains(document.activeElement)), true, "Tab must stay inside the modal");
      }
      await page.keyboard.press("Escape");
      await dialog.waitFor({ state: "hidden" });
      assert.equal(await launcher.evaluate(element => element === document.activeElement), true, "Closing import restores launcher focus");
      const dismissLauncher = jobButton("Dismiss");
      await dismissLauncher.click();
      await page.getByRole("button", { name: "Dismissed 1", exact: true }).waitFor();
      assert.equal(fixture.feedback.find(item => item.jobId === intern.id)?.reason, undefined, "Quick dismissal must not invent a reason");
      const reasonLauncher = page.getByRole("button", { name: "Add reason", exact: true });
      await reasonLauncher.click();
      const dismissDialog = page.getByRole("dialog", { name: "Add a dismissal reason" });
      await dismissDialog.waitFor();
      assert.equal(await dismissDialog.getByText(context, { exact: true }).isVisible(), true);
      assert.equal(await dismissDialog.getAttribute("aria-describedby"), "dismiss-role-context");
      assert.equal(await dismissDialog.getByRole("combobox", { name: "Reason" }).inputValue(), "");
      assert.equal(await dismissDialog.getByRole("combobox", { name: "Reason" }).evaluate(element => element === document.activeElement), true);
      await page.keyboard.press("Escape");
      await dismissDialog.waitFor({ state: "hidden" });
      assert.equal(await reasonLauncher.evaluate(element => element === document.activeElement), true);
      await reasonLauncher.click();
      await dismissDialog.getByRole("combobox", { name: "Reason" }).selectOption("Location is not right");
      authFeedback = true;
      await dismissDialog.getByRole("button", { name: "Save reason", exact: true }).click();
      await dismissDialog.getByRole("alert").getByText(/Sign in to open your workspace/).waitFor();
      assert.equal(await dismissDialog.getByRole("link", { name: "Sign in", exact: true }).getAttribute("href"), "/login");
      assert.doesNotMatch(await dismissDialog.getByRole("alert").innerText(), /AUTH_REQUIRED/);
      assert.equal(await page.locator(".inline-error").count(), 0, "Modal recovery must not duplicate the global error");
      const signInBounds = (await dismissDialog.getByRole("link", { name: "Sign in", exact: true }).boundingBox())!;
      const refreshBounds = (await dismissDialog.getByRole("button", { name: "Refresh workspace", exact: true }).boundingBox())!;
      assert.ok(refreshBounds.y >= signInBounds.y + signInBounds.height || refreshBounds.x >= signInBounds.x + signInBounds.width + 16, "Recovery controls need visible separation or a separate row");
      await page.screenshot({ path: `.data/matches-reason-recovery-${label}.png`, fullPage: true });
      await dismissDialog.getByRole("button", { name: "Refresh workspace", exact: true }).click();
      await dismissDialog.getByRole("alert").waitFor({ state: "hidden" });
      assert.equal(await dismissDialog.getByRole("combobox", { name: "Reason" }).inputValue(), "Location is not right", "In-dialog refresh preserves the reason draft");
      await page.keyboard.press("Escape");
      await dismissDialog.waitFor({ state: "hidden" });
      await reasonLauncher.click();
      assert.equal(await dismissDialog.getByRole("combobox", { name: "Reason" }).inputValue(), "Location is not right", "Reopening the same role preserves the reason draft");
      await dismissDialog.getByRole("button", { name: "Save reason", exact: true }).click();
      await dismissDialog.waitFor({ state: "hidden" });
      assert.equal(fixture.feedback.find(item => item.jobId === intern.id)?.reason, "Location is not right");
      await page.getByRole("button", { name: "Undo dismissal", exact: true }).click();
      await strongRole.waitFor();
      await jobButton("Dismiss").click();
      await page.getByRole("button", { name: "Add reason", exact: true }).click();
      await dismissDialog.getByRole("combobox", { name: "Reason" }).selectOption("Wrong role");
      await page.goto(`${origin}/login`);
      await page.goto(origin);
      await dismissDialog.waitFor();
      assert.equal(await dismissDialog.getByRole("combobox", { name: "Reason" }).inputValue(), "Wrong role", "Returning from sign-in retains the same applicant and role draft");
      await dismissDialog.getByRole("button", { name: "Save reason", exact: true }).click();
      await dismissDialog.waitFor({ state: "hidden" });
      assert.equal(fixture.feedback.find(item => item.jobId === intern.id)?.reason, "Wrong role");
      assert.equal(JSON.parse((await page.evaluate(owner => sessionStorage.getItem(`apply-ai:matches:${owner}`), fixture.profile.id))!).dismissDraft, undefined, "Saving clears the stored reason draft");
      await page.getByRole("button", { name: "Dismissed 1", exact: true }).click();
      await jobButton("Restore role").click();
      await page.getByRole("button", { name: "All roles 3", exact: true }).click();
      await strongRole.waitFor();
      if (label === "mobile") await page.getByRole("button", { name: /^Filter and sort/ }).click();
      assert.match(await strongRole.locator(".fit-evidence summary").getAttribute("aria-label") ?? "", /2 things to check/);
      assert.equal(await page.getByRole("button", { name: "Matches", exact: true }).getAttribute("aria-current"), "page");
      assert.equal(await page.getByRole("button", { name: "Any fit 3", exact: true }).getAttribute("aria-pressed"), "true");
      for (const control of await strongRole.locator(".small-actions button, .dark-button, .job-link").all()) {
        const box = await control.boundingBox();
        assert.ok(box && box.width >= 44 && box.height >= 44, "Job actions need at least 44px targets");
      }
      await page.getByRole("button", { name: "Saved 0", exact: true }).click();
      await page.getByRole("heading", { name: "Your shortlist starts here", exact: true }).waitFor();
      await page.getByRole("button", { name: "Browse matches", exact: true }).click();
      const previousSearch = await page.getByRole("searchbox", { name: /^Search roles or companies/ }).inputValue();
      malformedFeedback = true;
      await jobButton("Save").click();
      await strongRole.getByRole("alert").getByText("We couldn’t confirm whether your collection changes were saved. Refresh your workspace to check the latest status before trying again.", { exact: true }).waitFor();
      assert.equal(await jobButton("Save").isVisible(), true);
      assert.equal(await page.getByRole("searchbox", { name: /^Search roles or companies/ }).inputValue(), previousSearch);
      await strongRole.getByRole("button", { name: "Refresh workspace", exact: true }).click();
      await strongRole.getByRole("alert").waitFor({ state: "hidden" });
      failFeedback = true;
      await jobButton("Save").click();
      await strongRole.getByRole("alert").getByText("Feedback could not be saved. Try again.", { exact: true }).waitFor();
      assert.equal(await jobButton("Save").isVisible(), true, "Failed feedback must not invent a saved state");
      await strongRole.getByRole("button", { name: "Refresh workspace", exact: true }).click();
      await strongRole.getByRole("alert").waitFor({ state: "hidden" });
      slowFeedback = true;
      await jobButton("Save").click();
      await strongRole.getByText("Updating…", { exact: true }).waitFor();
      assert.equal(await jobButton("Save").isDisabled(), true);

      await jobButton("Unsave").waitFor();
      await page.getByRole("button", { name: "Saved 1", exact: true }).click();
      assert.equal(await page.getByRole("article").count(), 1);
      await page.getByRole("button", { name: "Strong 1", exact: true }).click();
      assert.equal(await page.getByRole("button", { name: "Saved 1", exact: true }).getAttribute("aria-pressed"), "true", "Fit changes must retain Saved scope");
      assert.equal(await page.getByRole("article").count(), 1);
      await page.getByRole("button", { name: "Uncertain 0", exact: true }).click();
      await page.getByRole("heading", { name: "No uncertain fit roles in saved", exact: true }).waitFor();
      await page.getByRole("button", { name: "Show any fit in this collection", exact: true }).click();
      await jobButton("Unsave").click();
      await page.getByRole("heading", { name: "Your shortlist starts here", exact: true }).waitFor();
      assert.equal(await page.locator("#matches-heading").evaluate(element => element === document.activeElement), true, "Unsave of the last Saved role hands focus to the heading");
      await page.getByRole("button", { name: "Browse matches", exact: true }).click();
      await jobButton("Save").click();
      await jobButton("Unsave").waitFor();
      await page.getByRole("button", { name: "Saved 1", exact: true }).click();
      await jobButton("Dismiss").click();
      await page.getByRole("button", { name: "Dismissed 1", exact: true }).waitFor();
      assert.equal(await page.getByRole("article").count(), 0);
      assert.equal(await page.getByRole("heading", { name: "Your next opportunities", exact: true }).evaluate(element => element === document.activeElement), true, "Removing the last visible role leaves focus at the view heading");
      await page.getByRole("button", { name: "Undo dismissal", exact: true }).click();
      await jobButton("Unsave").waitFor();
      assert.equal(await page.getByRole("article").count(), 1, "Undo restores both the role and its previous saved state");
      await page.getByRole("button", { name: "All roles 3", exact: true }).click();
      await jobButton("Dismiss").click();
      await page.getByRole("button", { name: "Dismissed 1", exact: true }).click();
      assert.equal(await page.getByRole("article").count(), 1);
      await jobButton("Restore role").click();
      await page.getByRole("heading", { name: "No dismissed roles", exact: true }).waitFor();
      assert.equal(await page.locator("#matches-heading").evaluate(element => element === document.activeElement), true, "Restore of the last Dismissed role hands focus to the heading");
      await page.getByRole("button", { name: "Browse matches", exact: true }).click();
      assert.equal(await page.getByRole("article").count(), 3);
      await page.getByRole("button", { name: "Close feedback message", exact: true }).click();
      await page.getByRole("button", { name: "Matches", exact: true }).focus();
      await page.keyboard.press("/");
      assert.equal(await query.evaluate(element => element === document.activeElement), true);
      await page.getByRole("button", { name: "Matches", exact: true }).focus();
      await page.keyboard.press("?");
      const keyboardHelp = page.locator("#matches-keyboard-help");
      assert.notEqual(await keyboardHelp.getAttribute("open"), null);
      assert.equal(await keyboardHelp.locator("summary").evaluate(element => element === document.activeElement), true);
      assert.equal(await keyboardHelp.getByText("Save or Unsave", { exact: true }).isVisible(), true);
      await page.screenshot({ path: `.data/matches-shortcuts-${label}.png` });
      await keyboardHelp.getByRole("checkbox", { name: "Enable keyboard shortcuts", exact: true }).uncheck();
      assert.equal(await page.locator("[aria-keyshortcuts]").count(), 0, "Disabled shortcuts must not be advertised to assistive technology");
      await keyboardHelp.locator("summary").click();
      const navMatches = page.getByRole("button", { name: "Matches", exact: true });
      await navMatches.focus();
      for (const key of ["/", "?", "j", "k"]) await page.keyboard.press(key);
      assert.equal(await navMatches.evaluate(element => element === document.activeElement), true, "Disabled global character shortcuts must preserve native focus");
      assert.equal(await keyboardHelp.getAttribute("open"), null);
      const requestsBeforeDisabledShortcuts = feedbackRequests;
      await strongRole.focus();
      for (const key of ["s", "d", "u"]) await page.keyboard.press(key);
      assert.equal(feedbackRequests, requestsBeforeDisabledShortcuts, "Disabled action shortcuts must not send mutations");
      assert.equal(JSON.parse((await page.evaluate(owner => sessionStorage.getItem(`apply-ai:matches:${owner}`), fixture.profile.id))!).shortcutsEnabled, false);
      await keyboardHelp.locator("summary").click();
      await keyboardHelp.getByRole("checkbox", { name: "Enable keyboard shortcuts", exact: true }).check();
      await keyboardHelp.locator("summary").click();
      await page.getByRole("button", { name: "Matches", exact: true }).focus();
      await page.keyboard.press("j");
      assert.equal(await page.getByRole("article").first().evaluate(element => element === document.activeElement), true);
      slowFeedback = true;
      const beforeShortcut = feedbackRequests;
      await page.keyboard.down("s"); await page.keyboard.down("s"); await page.keyboard.up("s");
      await jobButton("Unsave").waitFor();
      assert.equal(feedbackRequests, beforeShortcut + 1, "Holding Save must produce one feedback action");
      await page.keyboard.press("d");
      await strongRole.waitFor({ state: "hidden" });
      await page.getByRole("button", { name: "Undo dismissal", exact: true }).waitFor();
      await page.keyboard.press("u");
      await strongRole.waitFor();
      await jobButton("Unsave").waitFor();
      assert.equal(await strongRole.evaluate(element => element === document.activeElement), true, "Keyboard Undo restores role focus and saved state");
      await page.keyboard.press("d");
      await strongRole.waitFor({ state: "hidden" });
      await page.getByRole("button", { name: "Dismissed 1", exact: true }).click();
      await strongRole.waitFor(); await strongRole.focus(); await page.keyboard.press("d");
      await page.getByRole("heading", { name: "No dismissed roles", exact: true }).waitFor();
      await page.getByRole("button", { name: "Browse matches", exact: true }).click();
      await strongRole.focus(); await page.keyboard.press("s"); await jobButton("Unsave").waitFor();
      await page.keyboard.press("s"); await jobButton("Save").waitFor();
      const beforeTyping = feedbackRequests;
      await query.focus(); await page.keyboard.type("sdu");
      assert.equal(await query.inputValue(), "sdu");
      assert.equal(feedbackRequests, beforeTyping, "Typing must not invoke triage shortcuts");
      await query.fill("");
      await launcher.click();
      const url = page.getByRole("textbox", { name: "Job URL (required)", exact: true });
      assert.equal(await dialog.getByRole("button", { name: "Add role", exact: true }).isDisabled(), true);
      assert.ok(await url.evaluate(element => parseFloat(getComputedStyle(element).fontSize) >= 16));
      assert.ok((await url.boundingBox())!.height >= 44, "Import inputs retain touch sizing");
      await url.fill("http://company.example/role");
      await url.blur();
      assert.equal(await dialog.getByText("Use an HTTPS job link.", { exact: true }).isVisible(), true);
      await url.fill("https://boards.greenhouse.io/team/jobs/123");
      assert.equal(await dialog.getByRole("textbox", { name: "Company (required)", exact: true }).count(), 0);
      assert.equal(await dialog.getByRole("button", { name: "Add role", exact: true }).isEnabled(), true);
      await url.fill("https://company.example/careers/role");
      await dialog.getByRole("textbox", { name: "Company (required)", exact: true }).fill("Example");
      assert.equal(await dialog.getByRole("button", { name: "Add role", exact: true }).isDisabled(), true);
      await dialog.getByRole("textbox", { name: "Job title (required)", exact: true }).fill("Analyst");
      assert.equal(await dialog.getByRole("button", { name: "Add role", exact: true }).isEnabled(), true);
      authImport = true;
      await dialog.getByRole("button", { name: "Add role", exact: true }).click();
      await dialog.getByRole("alert").getByText(/Sign in to open your workspace/).waitFor();
      assert.equal(await dialog.getByRole("link", { name: "Sign in", exact: true }).getAttribute("href"), "/login");
      assert.doesNotMatch(await dialog.getByRole("alert").innerText(), /Check the link|AUTH_REQUIRED/);
      assert.equal(await page.locator(".inline-error").count(), 0, "Import recovery must not duplicate the global error");
      assert.equal(await url.inputValue(), "https://company.example/careers/role");
      assert.equal(await dialog.getByRole("button", { name: "Add role", exact: true }).isDisabled(), true, "Authentication must be recovered before resubmitting");
      await dialog.getByRole("button", { name: "Refresh workspace", exact: true }).click();
      await dialog.getByRole("alert").waitFor({ state: "hidden" });
      failImport = true;
      await dialog.getByRole("button", { name: "Add role", exact: true }).click();
      await dialog.getByRole("alert").getByText(/Posting unavailable/).waitFor();
      assert.equal(await url.inputValue(), "https://company.example/careers/role", "Failed import preserves the entered link");
      assert.equal(await dialog.getByRole("textbox", { name: "Company (required)", exact: true }).inputValue(), "Example");
      await page.screenshot({ path: `.data/matches-import-recovery-${label}.png`, fullPage: true });
      assert.equal(await dialog.getByRole("button", { name: "Refresh workspace", exact: true }).count(), 0, "A known posting failure should guide posting retry rather than status reconciliation");
      malformedImport = true;
      await dialog.getByRole("button", { name: "Try adding again", exact: true }).click();
      await dialog.getByRole("alert").getByText(/couldn’t confirm whether this role was added/).waitFor();
      assert.equal(await dialog.getByRole("button", { name: "Add role", exact: true }).isDisabled(), true, "An uncertain import outcome requires refreshing status before retrying");
      await page.screenshot({ path: `.data/matches-import-uncertain-${label}.png`, fullPage: true });
      failRefresh = true;
      await dialog.getByRole("button", { name: "Refresh workspace", exact: true }).click();
      await dialog.getByRole("alert").getByText(/Could not refresh your workspace/).waitFor();
      assert.match(await dialog.getByRole("alert").innerText(), /couldn’t confirm whether this role was added/);
      assert.equal(await dialog.getByRole("button", { name: "Add role", exact: true }).isDisabled(), true, "Failed reconciliation must keep repeat import blocked");
      await page.screenshot({ path: `.data/matches-import-refresh-failed-${label}.png`, fullPage: true });
      await page.keyboard.press("Escape");
      for (const name of ["Save", "Dismiss", "Prepare application for"]) assert.equal(await jobButton(name).isDisabled(), true, "Role action availability must match the reconciliation guard");
      await launcher.click();
      assert.equal(await dialog.getByRole("button", { name: "Add role", exact: true }).isDisabled(), true, "Reopening a dialog must not release an unresolved import guard");
      await dialog.getByRole("button", { name: "Refresh workspace", exact: true }).click();
      await dialog.getByRole("alert").waitFor({ state: "hidden" });
      assert.equal(await url.inputValue(), "https://company.example/careers/role", "In-dialog refresh preserves the import link");
      assert.equal(await dialog.getByRole("textbox", { name: "Company (required)", exact: true }).inputValue(), "Example");
      assert.equal(await dialog.getByRole("textbox", { name: "Job title (required)", exact: true }).inputValue(), "Analyst");
      await page.keyboard.press("Escape");
      await jobButton("Save").click();
      await page.getByRole("button", { name: "Saved 1", exact: true }).click();
      await page.getByRole("button", { name: "Strong 1", exact: true }).click();
      await query.fill("Cedar");
      await page.getByRole("combobox", { name: "Sort roles" }).selectOption("newest");
      await launcher.click();
      await page.reload();
      await dialog.waitFor();
      assert.equal(await url.inputValue(), "https://company.example/careers/role", "Reload restores the unfinished import");
      assert.equal(await dialog.getByRole("textbox", { name: "Company (required)", exact: true }).inputValue(), "Example");
      assert.equal(await query.inputValue(), "Cedar", "Reload restores the search");
      assert.equal(await page.getByRole("button", { name: "Saved 1", exact: true }).getAttribute("aria-pressed"), "true");
      assert.equal(await page.getByRole("button", { name: "Strong 1", exact: true, includeHidden: true }).getAttribute("aria-pressed"), "true");
      assert.equal(await page.getByRole("combobox", { name: "Sort roles", includeHidden: true }).inputValue(), "newest");
      await dialog.getByRole("button", { name: "Add role", exact: true }).click();
      await dialog.getByRole("button", { name: "Checking and adding…", exact: true }).waitFor();
      assert.equal(await dialog.getByRole("button", { name: "Checking and adding…", exact: true }).isDisabled(), true);
      assert.equal(await url.isDisabled(), true, "An in-flight import locks its submitted link");
      for (const field of ["Company (required)", "Job title (required)", "Location (optional)"]) assert.equal(await dialog.getByRole("textbox", { name: field, exact: true }).isDisabled(), true, "An in-flight import must not erase new edits on completion");
      await dialog.waitFor({ state: "hidden" });
      const imported = page.getByRole("article").filter({ has: page.getByRole("heading", { name: "Analyst", exact: true }) });
      await imported.waitFor();
      assert.equal(await page.getByRole("article").count(), 1, "Import reveals its specific opportunity, rather than the full list");
      assert.equal(await imported.evaluate(element => element === document.activeElement), true, "Import moves focus to its role");
      assert.equal(await page.locator(".feedback-summary").getByText("Added Analyst at Example. Review the posting details and fit below.", { exact: true }).isVisible(), true);
      await page.getByRole("button", { name: "Return to previous view", exact: true }).click();
      await strongRole.waitFor();
      assert.equal(await query.inputValue(), "Cedar");
      assert.equal(await page.getByRole("button", { name: "Saved 1", exact: true }).getAttribute("aria-pressed"), "true");
      assert.equal(await page.getByRole("button", { name: "Strong 1", exact: true, includeHidden: true }).getAttribute("aria-pressed"), "true");
      assert.equal(await page.getByRole("combobox", { name: "Sort roles", includeHidden: true }).inputValue(), "newest");
      await launcher.click();
      await url.fill("https://company.example/careers/role");
      await dialog.getByRole("textbox", { name: "Company (required)", exact: true }).fill("Example");
      await dialog.getByRole("textbox", { name: "Job title (required)", exact: true }).fill("Analyst");
      await dialog.getByRole("button", { name: "Add role", exact: true }).click();
      await dialog.getByRole("alert").getByText(/This role is already in your list/).waitFor();
      await dialog.getByRole("button", { name: "Review existing role", exact: true }).click();
      await imported.waitFor();
      assert.equal(fixture.jobs.length, 4, "Duplicate import recovery must not create another role");
      await page.getByRole("button", { name: "Return to previous view", exact: true }).click();
      await strongRole.waitFor();
      await launcher.click();
      await dialog.getByRole("button", { name: "Discard draft", exact: true }).click();
      assert.equal(await url.inputValue(), "https://company.example/careers/role", "Requesting discard preserves draft until confirmed");
      assert.equal(await dialog.getByRole("button", { name: "Add role", exact: true }).count(), 0, "Discard confirmation presents only its two choices");
      await page.screenshot({ path: `.data/matches-import-discard-${label}.png` });
      assert.equal(await dialog.getByRole("button", { name: "Keep editing", exact: true }).evaluate(element => element === document.activeElement), true, "Discard confirmation focuses its safe choice");
      await dialog.getByRole("button", { name: "Keep editing", exact: true }).click();
      assert.equal(await url.inputValue(), "https://company.example/careers/role");
      await dialog.getByRole("button", { name: "Discard draft", exact: true }).click();
      await page.keyboard.press("Escape");
      await launcher.click();
      assert.equal(await dialog.getByRole("button", { name: "Confirm discard", exact: true }).count(), 0, "Reopening starts without stale discard confirmation");
      await dialog.getByRole("button", { name: "Discard draft", exact: true }).click();
      await dialog.getByRole("button", { name: "Confirm discard", exact: true }).click();
      await dialog.waitFor({ state: "hidden" });
      await page.reload();
      await strongRole.waitFor();
      assert.equal(await dialog.count(), 0, "Discarded import must not reopen after reload");
      await launcher.click();
      assert.equal(await url.inputValue(), "", "Discard clears the stored import fields");
      await page.keyboard.press("Escape");
      await page.getByRole("button", { name: /^All roles / }).click();
      if (label === "mobile") await page.getByRole("button", { name: /^Filter and sort/ }).click();
      await page.getByRole("button", { name: /^Any fit / }).click();
      await query.fill("");
      await page.getByRole("combobox", { name: "Sort roles" }).selectOption("relevant");
      await page.evaluate(owner => sessionStorage.removeItem(`apply-ai:matches:${owner}`), fixture.profile.id);
      for (const kind of ["saved", "dismissed"] as const) {
        fixture = publicState(structuredClone(demoState));
        fixture.jobs.forEach(job => updateJobFeedback(fixture, { jobId: job.id, kind }));
        await page.reload();
        await page.getByRole("button", { name: kind === "saved" ? "Saved 3" : "Dismissed 3", exact: true }).click();
        const nextTitle = await page.getByRole("article").nth(2).getByRole("heading").innerText();
        await page.getByRole("article").nth(1).getByRole("button", { name: kind === "saved" ? /^Unsave / : /^Restore role / }).click();
        await page.waitForFunction(() => document.querySelectorAll(".job-row").length === 2);
        assert.equal(await page.getByRole("article").filter({ has: page.getByRole("heading", { name: nextTitle, exact: true }) }).evaluate(element => element === document.activeElement), true, `${kind} middle-row removal hands focus to the next role`);
        for (const remaining of [1, 0]) {
          await page.getByRole("article").first().getByRole("button", { name: kind === "saved" ? /^Unsave / : /^Restore role / }).click();
          await page.waitForFunction(count => document.querySelectorAll(".job-row").length === count, remaining);
        }
        assert.equal(await page.locator("#matches-heading").evaluate(element => element === document.activeElement), true);
        await page.evaluate(owner => sessionStorage.removeItem(`apply-ai:matches:${owner}`), fixture.profile.id);
      }
      fixture = publicState(structuredClone(demoState));
      const assessment = fixture.matches.find(item => item.jobId === intern.id)!.assessment;
      fixture.jobs = Array.from({ length: 12 }, (_, index) => ({ ...intern, id: `feedback-qa-${index}`, company: `QA Company ${index}`, title: `QA Role ${index}` }));
      fixture.matches = fixture.jobs.map(job => ({ jobId: job.id, assessment }));
      fixture.feedback = [];
      await page.reload();
      await page.getByRole("article").last().getByRole("button", { name: /^Dismiss / }).click();
      await page.waitForFunction(() => document.querySelectorAll(".job-row").length === 11);
      const undoBox = await page.getByRole("button", { name: "Undo dismissal", exact: true }).boundingBox();
      const chromeBox = (await page.locator(label === "mobile" ? ".sidebar" : ".topbar").boundingBox())!;
      assert.ok(undoBox && undoBox.y >= chromeBox.y + chromeBox.height && undoBox.y + undoBox.height <= height, "Lower-list Undo remains visible below navigation without scrolling back");
      const feedbackRail = page.locator(".matches-feedback-rail");
      const readingPane = page.getByRole("region", { name: "Matches workspace", exact: true });
      assert.ok(await readingPane.evaluate(element => element.scrollTop > 0), "Lower-list dismissal must exercise a scrolled reading pane");
      const railBounds = (await feedbackRail.boundingBox())!;
      const paneBounds = (await readingPane.boundingBox())!;
      assert.ok(railBounds.y + railBounds.height <= paneBounds.y + 1, "Persistent feedback must occupy reserved space outside the reading area");
      await readingPane.evaluate(element => element.scrollBy(0, -180));
      const scrolledRailBounds = (await feedbackRail.boundingBox())!;
      assert.equal(scrolledRailBounds.y, railBounds.y, "Undo stays visible while roles scroll independently");
      await page.screenshot({ path: `.data/matches-feedback-${label}.png` });
      await page.getByRole("button", { name: "Undo dismissal", exact: true }).click();
      await page.waitForFunction(() => document.querySelectorAll(".job-row").length === 12);
      assert.equal(await page.getByRole("article").last().evaluate(element => element === document.activeElement), true, "Undo returns focus to the restored role");
      await page.getByRole("button", { name: "Close feedback message", exact: true }).click();
      assert.equal(await page.getByRole("article").last().evaluate(element => element === document.activeElement), true, "Closing feedback retains role context");
      await page.evaluate(owner => sessionStorage.removeItem(`apply-ai:matches:${owner}`), fixture.profile.id);
      fixture = publicState(structuredClone(demoState));
      await page.reload();
      await strongRole.waitFor();
      await page.evaluate(() => window.scrollTo(0, 0));
      await page.screenshot({ path: `.data/matches-${label}.png`, fullPage: true });
      await page.screenshot({ path: `.data/matches-${label}-viewport.png` });
      const defaultPane = page.getByRole("region", { name: "Matches workspace", exact: true });
      await defaultPane.focus();
      await page.keyboard.press("PageDown");
      await page.waitForFunction(() => (document.querySelector(".matches-content-scroll")?.scrollTop ?? 0) > 100);
      assert.equal(await defaultPane.evaluate(element => element === document.activeElement), true, "The reading pane supports native keyboard scrolling without changing focus");
      await page.screenshot({ path: `.data/matches-pane-focus-${label}.png` });
      await defaultPane.evaluate(element => { element.scrollTop = element.scrollHeight; });
      await page.screenshot({ path: `.data/matches-end-${label}.png` });
      await defaultPane.evaluate(element => { element.scrollTop = 0; });
      fixture.lastRefreshAt = new Date().toISOString();
      fixture.discovery = { lastRefreshAt: new Date(Date.now() - 2 * 86400000).toISOString(), sources: [{ source: "first", status: "available", checkedAt: new Date().toISOString() }, { source: "second", status: "unavailable", checkedAt: new Date().toISOString() }], events: [] };
      await page.reload();
      await page.locator(".source-freshness").getByText("1 of 2 sources unavailable · Sources last checked 2 days ago", { exact: true }).waitFor();
      fixture.discovery.lastRefreshAt = undefined;
      await page.reload();
      await page.locator(".source-freshness").getByText("1 of 2 sources unavailable · Check time not reported", { exact: true }).waitFor();
      fixture.discovery = { sources: [], events: [] };
      await page.reload();
      await page.locator(".source-freshness").getByText("Waiting for the first source check", { exact: true }).waitFor();
      fixture.discovery = undefined;
      fixture.profile.demo = false;
      await page.reload();
      await page.locator(".source-freshness").getByText("Personal search", { exact: true }).waitFor();
      await page.getByRole("status", { name: "Personal search status", exact: true }).waitFor();
      fixture = publicState(structuredClone(demoState));
      fixture.automation.enabled = true;
      await page.reload();
      await strongRole.getByRole("button", { name: `Apply automatically for ${context}`, exact: true }).waitFor();
      assert.match((await page.locator("#application-mode-note").textContent()) ?? "", /can prepare and submit/);
      assert.doesNotMatch((await page.locator("#application-mode-note").textContent()) ?? "", /You approve materials/);
      await page.evaluate(owner => sessionStorage.removeItem(`apply-ai:matches:${owner}`), fixture.profile.id);
      console.log(`PASS ${label}: fit/search/counts/sort/disclosure, dialog keyboard behavior, touch targets, save/unsave, dismissal undo and restore`);
    }
    for (const [width, height] of [[320, 740], [820, 900], [720, 500]]) {
      await page.setViewportSize({ width, height });
      fixture = publicState(structuredClone(demoState));
      fixture.profile.demo = false;
      fixture.profile.name = "Invented QA applicant";
      fixture.jobs[0].title = "Early career software engineering and analytics opportunity — international product development team";
      fixture.jobs[0].company = "International technology research and development company";
      await page.goto(origin);
      if (width > 640) {
        const activityLauncher = page.getByRole("button", { name: "Activity", exact: true });
        await activityLauncher.click();
        await page.locator("#matches-activity").getByRole("heading", { name: "Agent activity", exact: true }).waitFor();
        await page.keyboard.press("Escape");
        assert.equal(await activityLauncher.evaluate(element => element === document.activeElement), true, "Tablet retains activity access and focus restoration");
      }
      await page.getByRole("article").first().waitFor();
      if (width <= 650) {
        await page.getByRole("button", { name: "More pages", exact: true }).click();
        assert.equal(await page.locator("#more-pages").getByRole("button", { name: "Sign out", exact: true }).isVisible(), true);
        assert.equal(await page.locator("#more-pages").getByText("Workspace: Invented QA applicant", { exact: true }).isVisible(), true);
        await page.screenshot({ path: ".data/matches-account-mobile.png" });
        await page.keyboard.press("Escape");
      } else {
        assert.equal(await page.locator(".tablet-signout").isVisible(), true, "Tablet retains account exit");
        if (width === 820) await page.screenshot({ path: ".data/matches-account-tablet.png" });
      }
      assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), `Long-content layout must not overflow at ${width}px`);
      for (const name of ["Matches", "Applications", "Profile", "Search settings"]) {
        const navigation = page.getByRole("button", { name, exact: true });
        assert.ok(await navigation.evaluate(element => parseFloat(getComputedStyle(element).fontSize) >= 10), `Navigation labels stay visible at ${width}px`);
      }
      if (width <= 650) {
        const boxes = await page.locator(".collection-filter").evaluateAll(elements => elements.map(element => { const box = element.getBoundingClientRect(); return { top: box.top, height: box.height }; }));
        assert.equal(new Set(boxes.map(box => box.top)).size, 1, "Collection controls stay on one readable row at narrow widths");
        assert.ok(boxes.every(box => box.height >= 44));
      }
      console.log(`PASS responsive ${width}x${height}: long content, visible navigation, no horizontal overflow`);
    }
    const sameTitlePage = await browser.newPage({ viewport: { width: 390, height: 844 } });
    const sameTitleState = structuredClone(demoState);
    sameTitleState.jobs[1].title = intern.title; sameTitleState.jobs[1].company = "Same-title employer";
    const sameTitleFixture = publicState(sameTitleState);
    await sameTitlePage.route("**/api/state", route => route.fulfill({ json: sameTitleFixture }));
    await sameTitlePage.route("**/api/actions", async route => {
      const body = route.request().postDataJSON(); assert.equal(body.action, "feedback");
      assert.equal(body.payload.jobId, sameTitleState.jobs[1].id);
      updateJobFeedback(sameTitleFixture, body.payload); await route.fulfill({ json: { ok: true } });
    });
    await sameTitlePage.goto(origin);
    const sameTitleRole = sameTitlePage.getByRole("article", { name: `${intern.title} Same-title employer`, exact: true });
    await sameTitleRole.waitFor();
    await sameTitleRole.getByRole("button", { name: `Save ${intern.title} at Same-title employer`, exact: true }).click();
    await sameTitlePage.locator(".feedback-summary").getByText(`${intern.title} at Same-title employer saved.`, { exact: true }).waitFor();
    await sameTitleRole.getByRole("button", { name: `Dismiss ${intern.title} at Same-title employer`, exact: true }).click();
    await sameTitleRole.waitFor({ state: "hidden" });
    assert.match((await sameTitlePage.locator(".feedback-summary").textContent()) ?? "", /^Dismissed: Software Engineering Intern at Same-title employer\./);
    await sameTitlePage.getByRole("button", { name: "Undo dismissal", exact: true }).click();
    await sameTitlePage.locator(".feedback-summary").getByText(`${intern.title} at Same-title employer is back in your matches.`, { exact: true }).waitFor();
    await sameTitleRole.waitFor(); await sameTitlePage.close();
    console.log("PASS identical titles: Save, Dismiss and Undo identify the employer");
    const personalPage = await browser.newPage({ viewport: { width: 390, height: 844 } });
    const personalState = structuredClone(demoState);
    personalState.profile.demo = false;
    personalState.profile.name = "Invented QA";
    personalState.personalSearch = { status: "complete", requestId: "qa-request", profileKey: "qa-profile", requestedAt: new Date().toISOString(), completedAt: new Date().toISOString(), jobs: personalState.jobs };
    let personalFixture = publicState(personalState);
    let personalConditional = false;
    await personalPage.clock.install();
    await personalPage.route("**/api/state", route => route.fulfill(personalConditional ? { status: 304 } : { json: personalFixture, headers: { ETag: "qa-personal" } }));
    await personalPage.route("**/api/actions", () => assert.fail("Personal-search presentation checks must not write workspace data"));
    await personalPage.goto(origin); await personalPage.getByRole("article").first().waitFor();
    assert.equal(await personalPage.getByRole("status", { name: "Personal search status" }).isVisible(), false, "Routine completed-search detail belongs in the disclosure");
    const personalPrepare = await personalPage.getByRole("article").first().getByRole("button", { name: /^Prepare application for/ }).boundingBox();
    assert.ok(personalPrepare && personalPrepare.y + personalPrepare.height <= 844, "The completed personal-search banner must not push the first role action out of view");
    await personalPage.screenshot({ path: ".data/matches-personal-mobile.png" });
    assert.match((await personalPage.locator(".source-freshness").textContent()) ?? "", /checked just now/);
    personalConditional = true;
    await personalPage.clock.fastForward(120_000);
    await personalPage.locator(".source-freshness").getByText("Your search checked 2 minutes ago", { exact: true }).waitFor();
    personalConditional = false;
    const searchStatus = personalPage.locator(".search-status");
    await searchStatus.locator("summary").click();
    assert.equal(await searchStatus.locator("time").getAttribute("datetime"), personalState.personalSearch.completedAt);
    assert.ok((await searchStatus.locator("time").textContent())?.length, "Search status exposes the exact check timestamp separately from workspace updates");
    personalFixture.onboarding = { ...personalFixture.onboarding, complete: true, missing: [] };
    personalFixture.automation = { ...personalFixture.automation, enabled: false, paused: false };
    await personalPage.reload();
    await searchStatus.locator("summary").click();
    await searchStatus.getByText("Automation is off", { exact: true }).waitFor();
    assert.equal(await searchStatus.getByText("Finish setup before enabling automation", { exact: true }).count(), 0);
    await searchStatus.getByRole("button", { name: "Edit search preferences", exact: true }).click();
    assert.equal(await personalPage.locator("#search-preferences").evaluate(element => element === document.activeElement), true);
    const emptyState = structuredClone(personalState);
    emptyState.jobs = []; emptyState.importedJobs = []; emptyState.applications = []; emptyState.personalSearch = undefined;
    emptyState.profile.facts = []; emptyState.profile.preferredTitles = []; emptyState.profile.preferredLocations = []; emptyState.profile.remoteOnly = false; emptyState.profile.searchPreferencesConfirmedAt = undefined;
    personalFixture = publicState(emptyState);
    await personalPage.getByRole("button", { name: "Matches", exact: true }).click();
    await personalPage.goto(origin);
    await personalPage.getByRole("heading", { name: "Your personal search starts here", exact: true }).waitFor();
    assert.equal(await personalPage.locator(".collectionbar, .job-search, .matches-controls, .setup-context").count(), 0, "A fresh empty account needs setup, not zero-result filters");
    const emptySetup = personalPage.locator(".empty").getByRole("button", { name: "Set up my profile", exact: true });
    assert.equal(await emptySetup.isVisible(), true);
    await personalPage.screenshot({ path: ".data/matches-empty-mobile.png" });
    await emptySetup.click();
    assert.equal(await personalPage.locator("#confirmed-resume-facts").evaluate(element => element === document.activeElement), true);
    await personalPage.getByRole("button", { name: "Matches", exact: true }).click();
    for (const status of ["failed", "budget_limited"] as const) {
      personalState.jobs = []; personalState.importedJobs = []; personalState.applications = [];
      personalState.personalSearch = { ...personalState.personalSearch!, status, jobs: [] };
      personalFixture = publicState(personalState);
      await personalPage.goto(origin);
      const notice = personalPage.getByRole("status", { name: "Personal search status" });
      await notice.waitFor();
      if (status === "failed") {
        assert.match((await notice.textContent()) ?? "", /every four hours/);
        await notice.getByRole("button", { name: "Import a posting", exact: true }).click();
        await personalPage.getByRole("dialog", { name: "Import a job link", exact: true }).waitFor();
        await personalPage.keyboard.press("Escape");
      } else {
        assert.match((await notice.textContent()) ?? "", /00:00 UTC on the first day/);
        assert.equal(await notice.getByRole("link", { name: "Review AI usage", exact: true }).getAttribute("href"), "/usage");
      }
    }
    await personalPage.close();
    console.log("PASS personal-search states: compact completed status, first role action, focused setup, failed-search import and monthly budget recovery");
    const batchPage = await browser.newPage({ viewport: { width: 390, height: 844 } });
    const batchState = structuredClone(demoState);
    batchState.jobs = Array.from({ length: 4 }, (_, index) => ({ ...intern, id: `batch-${index}`, company: `QA Batch ${index}`, url: `https://example.com/batch-${index}` }));
    batchState.importedJobs = []; batchState.applications = [];
    updateJobFeedback(batchState, { jobId: "batch-0", kind: "saved" });
    let batchFixture = publicState(batchState); let batchCalls = 0; let failBatch = true;
    let releaseBatch: (() => void) | undefined; let slowBatch = false;
    let ambiguousBatch = false; let failedBatchRefresh = false;
    await batchPage.route("**/api/state", route => route.fulfill(failedBatchRefresh ? { status: 503, json: { error: "Temporary refresh failure" } } : { json: batchFixture }));
    await batchPage.route("**/api/actions", async route => {
      const body = route.request().postDataJSON();
      assert.equal(body.action, "feedback"); assert.equal(body.payload.kind, "saved");
      assert.equal(body.payload.expectedKind, "clear"); assert.equal(body.payload.expectedOwnerId, batchFixture.profile.id);
      batchCalls++;
      if (ambiguousBatch) {
        ambiguousBatch = false; failedBatchRefresh = true;
        updateJobFeedback(batchFixture, body.payload);
        return route.fulfill({ status: 200, contentType: "application/json", body: "unreadable" });
      }
      if (failBatch && batchCalls === 2) return route.fulfill({ status: 503, json: { error: "A role could not be saved. Try again." } });
      if (slowBatch) { slowBatch = false; await new Promise<void>(resolve => { releaseBatch = resolve; }); }
      updateJobFeedback(batchFixture, body.payload); return route.fulfill({ json: { ok: true } });
    });
    await batchPage.goto(origin); await batchPage.getByRole("article").first().waitFor();
    await batchPage.getByRole("searchbox", { name: /^Search roles or companies/ }).fill("QA Batch");
    await batchPage.getByRole("button", { name: /^Filter and sort/ }).click();
    await batchPage.getByRole("button", { name: "Save 3 unsaved roles in this view", exact: true }).click();
    await batchPage.locator(".feedback-summary").getByText("Interrupted. 1/3 saves confirmed.", { exact: true }).waitFor();
    assert.equal(batchCalls, 2, "Stop after the first failed request");
    assert.equal(batchFixture.feedback.filter(item => item.kind === "saved").length, 2, "Keep the completed save and original bookmark");
    failBatch = false;
    await batchPage.getByRole("button", { name: "Save 2 unsaved roles in this view", exact: true }).click();
    await batchPage.locator(".feedback-summary").getByText("Saved 2 roles.", { exact: true }).waitFor();
    await batchPage.waitForFunction(() => document.activeElement?.getAttribute("data-match-action") === "review-saved");
    assert.equal(batchCalls, 4, "Retry only the remaining unsaved roles");
    await batchPage.getByRole("button", { name: "Review saved", exact: true }).click();
    assert.equal(await batchPage.getByRole("article").count(), 4);
    await batchPage.getByRole("button", { name: "Return to previous view", exact: true }).click();
    batchFixture = publicState(structuredClone(batchState)); batchCalls = 0; slowBatch = true;
    await batchPage.reload(); await batchPage.getByRole("article").first().waitFor();
    await batchPage.getByRole("button", { name: /^Filter and sort/ }).click();
    await batchPage.getByRole("button", { name: "Save 3 unsaved roles in this view", exact: true }).click();
    assert.equal(await batchPage.getByRole("searchbox", { name: /^Search roles or companies/ }).isDisabled(), true);
    assert.equal(await batchPage.getByRole("combobox", { name: "Sort roles", exact: true }).isDisabled(), true);
    await batchPage.getByRole("button", { name: "Stop further saves", exact: true }).click();
    await batchPage.getByRole("button", { name: "Stopping…", exact: true }).waitFor();
    while (!releaseBatch) await batchPage.waitForTimeout(10);
    releaseBatch();
    await batchPage.locator(".feedback-summary").getByText("Stopped. Saved 1/3.", { exact: true }).waitFor();
    assert.equal(await batchPage.getByRole("searchbox", { name: /^Search roles or companies/ }).isDisabled(), false);
    assert.equal(batchCalls, 1, "Stopping finishes the in-flight bookmark without starting another");
    await batchPage.screenshot({ path: ".data/matches-batch-mobile.png" });
    batchFixture = publicState(structuredClone(batchState)); batchCalls = 0; ambiguousBatch = true;
    await batchPage.reload(); await batchPage.getByRole("article").first().waitFor();
    await batchPage.getByRole("button", { name: /^Filter and sort/ }).click();
    const saveView = batchPage.getByRole("button", { name: "Save 3 unsaved roles in this view", exact: true });
    await saveView.click();
    const batchRecovery = batchPage.getByRole("alert").filter({ hasText: "The save status could not be refreshed" });
    await batchRecovery.waitFor();
    const refreshBatch = batchRecovery.getByRole("button", { name: "Refresh workspace", exact: true });
    await batchPage.waitForFunction(() => document.activeElement?.closest('.workspace-recovery-actions') !== null && document.activeElement?.textContent === "Refresh workspace");
    assert.equal(await refreshBatch.evaluate(element => element === document.activeElement), true, "Zero-confirmed batch failure must focus the usable recovery action");
    const recoveryContrast = () => refreshBatch.evaluate(element => {
      const style = getComputedStyle(element);
      const [foreground, background] = [style.color, style.backgroundColor].map(color => {
        const channels = color.match(/[\d.]+/g)!.slice(0, 3).map(value => Number(value) / 255).map(value => value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4);
        return channels[0] * 0.2126 + channels[1] * 0.7152 + channels[2] * 0.0722;
      });
      return (Math.max(foreground, background) + 0.05) / (Math.min(foreground, background) + 0.05);
    });
    await batchPage.mouse.move(0, 0);
    assert.ok(await recoveryContrast() >= 4.5, "Recovery label needs AA contrast when focused");
    await refreshBatch.hover();
    assert.ok(await recoveryContrast() >= 4.5, "Recovery label needs AA contrast on hover too");
    assert.equal(await saveView.isDisabled(), true, "Uncertain batch outcomes stay gated after a failed reconciliation");
    assert.equal(await batchPage.getByRole("article").locator('[data-match-action="save"]').first().isDisabled(), true, "Individual writes stay gated too");
    await refreshBatch.click();
    await batchPage.getByRole("alert").filter({ hasText: "Could not refresh your workspace" }).waitFor();
    assert.equal(await saveView.isDisabled(), true, "Repeated refresh failure must not release uncertainty");
    assert.equal(batchCalls, 1, "No automatic mutation retry after an unreadable success response");
    await batchPage.screenshot({ path: ".data/matches-batch-uncertain-mobile.png" });
    failedBatchRefresh = false;
    await batchPage.getByRole("button", { name: "Refresh workspace", exact: true }).click();
    await batchPage.getByRole("button", { name: "Save 2 unsaved roles in this view", exact: true }).waitFor();
    assert.equal(await batchPage.getByRole("button", { name: "Save 2 unsaved roles in this view", exact: true }).isDisabled(), false);
    assert.equal(batchCalls, 1, "Successful reconciliation reveals the accepted save without repeating it");
    await batchPage.close();
    console.log("PASS filtered-view saving: guarded owner/collection requests, partial-failure recovery, retry unsaved roles, Saved navigation and stopping after in-flight save");
    if (process.env.TEST_MATCHES_SKIP_CONNECTION === "1") {
      console.log("SKIP unchanged connection checks by explicit focused-test setting");
      return;
    }
    const connectionPage = await browser.newPage({ viewport: { width: 390, height: 844 } });
    const connectionFixture = publicState(structuredClone(demoState));
    let failedUpdates = false; let expiredUpdates = false;
    let failedChecks = 0;
    await connectionPage.route("**/api/state", route => {
      if (failedUpdates) failedChecks++;
      return route.fulfill(failedUpdates ? { status: 503, json: { error: "Temporary connection failure" } } : expiredUpdates ? { status: 401, json: { error: "AUTH_REQUIRED" } } : { json: connectionFixture });
    });
    await connectionPage.route("**/api/actions", () => assert.fail("Connection checks must not write workspace data"));
    await connectionPage.bringToFront();
    await connectionPage.goto(origin); await connectionPage.getByRole("article").first().waitFor();
    assert.equal(await connectionPage.evaluate(() => document.hidden), false, "Connection checks require a visible workspace");
    failedUpdates = true;
    const connectionNotice = connectionPage.locator(".workspace-connection");
    try { await connectionNotice.waitFor({ timeout: 60_000 }); }
    catch (error) { console.error("Connection test diagnostics", { failedChecks, hidden: await connectionPage.evaluate(() => document.hidden) }); throw error; }
    assert.match((await connectionNotice.textContent()) ?? "", /updates are paused/);
    assert.equal(await connectionPage.getByRole("article").count(), 3, "Interrupted updates retain the last received list");
    await connectionPage.screenshot({ path: ".data/matches-connection-mobile.png" });
    failedUpdates = false;
    await connectionNotice.getByRole("button", { name: "Retry updates", exact: true }).click();
    await connectionNotice.waitFor({ state: "hidden" });
    expiredUpdates = true;
    await connectionPage.evaluate(() => document.dispatchEvent(new Event("visibilitychange")));
    await connectionNotice.getByRole("link", { name: "Sign in", exact: true }).waitFor();
    assert.equal(await connectionNotice.getByRole("link", { name: "Sign in", exact: true }).getAttribute("href"), "/login");
    assert.equal(await connectionPage.getByRole("article").count(), 3);
    await connectionPage.close();
    console.log("PASS connection recovery: persistent failure notice, retained roles, Retry updates and expired-session sign-in");
  } finally { await browser.close(); }
}

main().catch(error => { console.error(error); process.exitCode = 1; });
